version: '3'
services:  
  nginx:
    build: nginx/
    container_name: nginx-django
    volumes:
      - ./django/aslm:/src
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8000:8000"
    depends_on:
      - web
  web:
    build: ./django/
    container_name: aslm-django-guinicorn
    depends_on:
      - db
    volumes:
      - ./django/aslm:/src
    expose:
      - "8000"
    links:
      - redis
  db:
    image: postgres:latest
    container_name: postgredb-django
  redis:
    build: ./redis
    container_name: redis
    ports:
     - '6378:6378'
