version: '3'
services:  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./aslm:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: aslm_django_guinicorn
    depends_on:
      - db
    volumes:
      - ./aslm:/src
    expose:
      - "8000"
    links:
      - redis
  db:
    image: postgres:latest
    container_name: postgredb
  redis:
    build: ./config/redis
    container_name: redis
    ports:
     - '6378:6378'
