FROM python:3.6

MAINTAINER Adil MOUHSSINE

RUN apt-get update && \
   apt-get install -y \
   git \
   vim \
   && rm -rf /var/lib/apt/lists/*
ENV PYTHONUNBUFFERED 1
ENV C_FORCE_ROOT true
RUN mkdir src
WORKDIR /src
COPY  requirements.txt .
COPY ./aslm .

# install project dependencies
RUN pip install -r requirements.txt
